name: pymc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy<2.0
  - pandas
  - scikit-learn
  - matplotlib
  - scipy
  - yfinance
  - lightgbm
  - xgboost
  - dynesty
  - pip
  - ipykernel
